version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"


  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    
  
  minio:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER=minio_root
      - MINIO_ROOT_PASSWORD=minio_password
    ports:
      - "9000:9000"
      - "9090:9090"

  createbuckets:
    image: minio/mc:RELEASE.2022-12-24T15-21-38Z
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      mc alias set my_minio http://minio:9000 minio_root minio_password;
      mc mb --ignore-existing my_minio/default-bucket;
      "

volumes:
  minio:
    driver: local
